
# Load the country_safety.json file generated by build_country_safety.py
with open('country_safety.json', 'r', encoding='utf-8') as f:
    safety_data = json.load(f)

# Convert to DataFrame
safety_list = []
for code, data in safety_data.items():
    risk_scores = data.get('risk_scores', {})
    safety_list.append({
        'code': code,
        'name': data.get('name', ''),
        'region': data.get('region', ''),
        'overall_risk': data.get('overall_risk', 'unknown'),
        'crime_score': risk_scores.get('crime', 3),
        'political_score': risk_scores.get('political', 3),
        'health_score': risk_scores.get('health', 3),
        'natural_disaster_score': risk_scores.get('natural_disaster', 3),
        'is_core_country': data.get('is_core_country', False)
    })

df_safety = pd.DataFrame(safety_list)
print(f"✓ Loaded safety data for {len(df_safety)} countries")
df_safety.head()
